### PR TITLE
Standarize post-deployment actions through drush deploy command

### PR DESCRIPTION
**Pull request by dlopez-akalam**

### CODE REVIEW

**Comment by dlopez-akalam** [comment]
See https://www.drush.org/latest/deploycommand/

**Comment by dlopez-akalam** [comment]
drush deploy command is only present on drush 10.3+ we should check which version of drush is installed on all projects before merging

**Review by rsanzante — COMMENTED** [review]
Initially, we run front end build tasks and then clear cache:

```
$DOCKER_EXEC_NPM sh ${DOCKER_PROJECT_ROOT}/scripts/frontend-build.sh ${NPM_RUN_COMMAND}

$DOCKER_EXEC_PHP drush @${LOCAL_ALIAS} cr
```

However, using deploy we have:
```
  $DOCKER_EXEC_PHP drush @${LOCAL_ALIAS} deploy -y

  $DOCKER_EXEC_NPM sh ${DOCKER_PROJECT_ROOT}/scripts/frontend-build.sh ${NPM_RUN_COMMAND}
```
That means the cache clear is done before frontend-build. We may need to add a drush cr after the deploy command.

**Comment by dlopez-akalam** [comment]
Since the assets are not cached until the site is accessed, I think an extra cache-rebuild isn't really needed. However, if you feel is safer, we could run frontend-build first, and then call drush deploy at the end

**Comment by dlopez-akalam** [comment]
@rsanzante after merging https://github.com/Metadrop/scripthor/pull/13 , incorporing a new command to import translations could increase the need of an extra cache-rebuild, so we are adding back the extra drush cr call

**Comment by dlopez-akalam** [comment]
This PR is deprecated because locale-check and locale-import should be applied before config-import, so drush deploy command cannot be used

**Pull request closed without merging**
